#!/usr/bin/env ruby

require "bundler/setup"
require './app/report_extractor_worker'
require './app/report_generator'
require 'sidekiq/api'

# You can add fixtures and/or initialization code here to make experimenting
# with your gem easier. You can also use a different console, if you like.

# (If you use this, don't forget to add pry to your Gemfile!)
# require "pry"
# Pry.start

require "irb"
IRB.start
